### PR TITLE
Pandana v0.4.4

### PR DESCRIPTION
**Pull request by smmaurer**
@conda-forge-admin, please rerender

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by smmaurer** [comment]
@conda-forge-admin, please rerender

**Comment by smmaurer** [comment]
Hi @conda-forge/core,

This version of the package was fixed to allow compilation in VisualStudio 2008 for Windows Python 2.7 (by refactoring to no longer require C++11).

I tried to re-enable that build environment, but something is not working -- the re-render failed above. Do you have any ideas?

Per [these instructions](https://conda-forge.org/docs/maintainer/infrastructure.html#using-azure-for-everything), VisualStudio 2008 requires switching back from Azure to AppVeyor for the Windows builds.

**Comment by isuruf** [comment]
I've restarted the webapp. (This happens sometimes). Please try again in five minutes and let us know if it doesn't.

**Comment by smmaurer** [comment]
@conda-forge-admin, please rerender

**Comment by smmaurer** [comment]
@conda-forge-admin, please rerender

**Comment by smmaurer** [comment]
Closing this in favor of #7

**Pull request closed without merging**
